import { Player, Match, LeagueStanding, NewsArticle, TicketTier, Product, User } from '../models/types.js';

export const mockPlayers: Player[] = [
  {
    id: 'p-1',
    number: 1,
    name: 'Fasil Gebremichael',
    amharicName: 'ፋሲል ገብረሚካኤል',
    position: 'Goalkeeper',
    nationality: 'Ethiopia',
    age: 25,
    appearances: 22,
    goals: 0,
    assists: 0,
    cleanSheets: 10,
    image: 'https://images.unsplash.com/photo-1543326727-cf6c39e8f84c?w=600&auto=format&fit=crop&q=80',
    biography: 'First-choice goalkeeper and Ethiopian national team shot-stopper known for lightning reflexes and commanding penalty box presence.',
    isCaptain: false,
  },
  {
    id: 'p-2',
    number: 4,
    name: 'Salamlak Tegegn',
    amharicName: 'ሰላምላክ ተገኝ',
    position: 'Defender',
    nationality: 'Ethiopia',
    age: 27,
    appearances: 24,
    goals: 2,
    assists: 1,
    image: 'https://images.unsplash.com/photo-1574629810360-7efbbe195018?w=600&auto=format&fit=crop&q=80',
    biography: 'A stalwart center-back whose composure and aerial dominance have fortified the Waves of Tana defense for 4 seasons.',
    isCaptain: true,
  },
  {
    id: 'p-3',
    number: 5,
    name: 'Menaf Awol',
    amharicName: 'መናፍ አወል',
    position: 'Defender',
    nationality: 'Ethiopia',
    age: 24,
    appearances: 20,
    goals: 1,
    assists: 3,
    image: 'https://images.unsplash.com/photo-1560272564-c83b66b1ad12?w=600&auto=format&fit=crop&q=80',
    biography: 'Dynamic full-back with blistering pace on the overlap and exceptional recovery tackling ability.',
    isCaptain: false,
  },
  {
    id: 'p-4',
    number: 8,
    name: 'Alelegn Azene',
    amharicName: 'አለልኝ አዘነ',
    position: 'Midfielder',
    nationality: 'Ethiopia',
    age: 26,
    appearances: 23,
    goals: 5,
    assists: 7,
    image: 'https://images.unsplash.com/photo-1517466787929-bc90951d0974?w=600&auto=format&fit=crop&q=80',
    biography: 'Playmaker and midfield orchestrator possessing vision, pinpoint passing range, and deadly set-piece execution.',
    isCaptain: false,
  },
  {
    id: 'p-5',
    number: 10,
    name: 'Fuad Fereje',
    amharicName: 'ፉአድ ፈረጃ',
    position: 'Midfielder',
    nationality: 'Ethiopia',
    age: 23,
    appearances: 21,
    goals: 6,
    assists: 8,
    image: 'https://images.unsplash.com/photo-1508098682722-e99c43a406b2?w=600&auto=format&fit=crop&q=80',
    biography: 'Creative attacking midfielder capable of unlocking deep defensive blocks with intricate dribbling.',
    isCaptain: false,
  },
  {
    id: 'p-6',
    number: 9,
    name: 'Habtamu Taddese',
    amharicName: 'ሀብታሙ ታደሰ',
    position: 'Forward',
    nationality: 'Ethiopia',
    age: 26,
    appearances: 24,
    goals: 14,
    assists: 5,
    image: 'https://images.unsplash.com/photo-1518609878373-06d740f60d8b?w=600&auto=format&fit=crop&q=80',
    biography: 'Prolific center forward and top scorer for the club, renowned for clinical finishing and relentless pressing.',
    isCaptain: false,
  },
  {
    id: 'p-7',
    number: 11,
    name: 'Chernet Gugsa',
    amharicName: 'ቸርነት ጉግሳ',
    position: 'Forward',
    nationality: 'Ethiopia',
    age: 24,
    appearances: 19,
    goals: 8,
    assists: 6,
    image: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=600&auto=format&fit=crop&q=80',
    biography: 'Explosive winger with electrifying trickery who thrives in one-on-one scenarios on the flanks.',
    isCaptain: false,
  },
  {
    id: 'p-8',
    number: 18,
    name: 'Frezer Kassa',
    amharicName: 'ፍሬዘር ካሳ',
    position: 'Defender',
    nationality: 'Ethiopia',
    age: 22,
    appearances: 18,
    goals: 0,
    assists: 2,
    image: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=600&auto=format&fit=crop&q=80',
    biography: 'Youth academy graduate making tremendous strides in first-team defense.',
    isCaptain: false,
  }
];

export const mockMatches: Match[] = [
  {
    id: 'm-1',
    competition: 'BetKing Ethiopian Premier League',
    round: 'Matchday 25',
    homeTeam: 'Bahir Dar Kenema',
    awayTeam: 'Saint George SC',
    date: '2026-10-04',
    time: '16:00',
    venue: 'Bahir Dar International Stadium',
    status: 'UPCOMING',
    isHome: true,
    clubLogo: 'https://placehold.co/100x100/104f55/ffffff?text=BDK',
    opponentLogo: 'https://placehold.co/100x100/dc2626/ffffff?text=STG',
  },
  {
    id: 'm-2',
    competition: 'BetKing Ethiopian Premier League',
    round: 'Matchday 26',
    homeTeam: 'Ethiopian Coffee SC',
    awayTeam: 'Bahir Dar Kenema',
    date: '2026-10-11',
    time: '15:00',
    venue: 'Abebe Bikila Stadium, Addis Ababa',
    status: 'UPCOMING',
    isHome: false,
    clubLogo: 'https://placehold.co/100x100/104f55/ffffff?text=BDK',
    opponentLogo: 'https://placehold.co/100x100/854d0e/ffffff?text=COF',
  },
  {
    id: 'm-3',
    competition: 'BetKing Ethiopian Premier League',
    round: 'Matchday 24',
    homeTeam: 'Bahir Dar Kenema',
    awayTeam: 'Fasil Kenema SC',
    homeScore: 2,
    awayScore: 1,
    date: '2026-09-21',
    time: '16:00',
    venue: 'Bahir Dar International Stadium',
    status: 'COMPLETED',
    isHome: true,
    clubLogo: 'https://placehold.co/100x100/104f55/ffffff?text=BDK',
    opponentLogo: 'https://placehold.co/100x100/ca8a04/ffffff?text=FAS',
    events: [
      { minute: 34, type: 'goal', player: 'Habtamu Taddese', team: 'Bahir Dar Kenema' },
      { minute: 58, type: 'goal', player: 'Alelegn Azene', team: 'Bahir Dar Kenema' },
      { minute: 81, type: 'goal', player: 'Getaneh Kebede', team: 'Fasil Kenema SC' },
    ]
  },
  {
    id: 'm-4',
    competition: 'BetKing Ethiopian Premier League',
    round: 'Matchday 23',
    homeTeam: 'Meqele 70 Enderta',
    awayTeam: 'Bahir Dar Kenema',
    homeScore: 0,
    awayScore: 2,
    date: '2026-09-14',
    time: '15:00',
    venue: 'Tigray Stadium',
    status: 'COMPLETED',
    isHome: false,
    clubLogo: 'https://placehold.co/100x100/104f55/ffffff?text=BDK',
    opponentLogo: 'https://placehold.co/100x100/b91c1c/ffffff?text=MEQ',
    events: [
      { minute: 42, type: 'goal', player: 'Fuad Fereje', team: 'Bahir Dar Kenema' },
      { minute: 88, type: 'goal', player: 'Chernet Gugsa', team: 'Bahir Dar Kenema' },
    ]
  }
];

export const mockStandings: LeagueStanding[] = [
  {
    position: 1,
    team: 'Bahir Dar Kenema SC',
    played: 24,
    won: 16,
    drawn: 5,
    lost: 3,
    goalsFor: 44,
    goalsAgainst: 18,
    goalDifference: 26,
    points: 53,
    form: ['W', 'W', 'W', 'D', 'W'],
    logo: 'https://placehold.co/60x60/104f55/ffffff?text=BDK',
    isBDK: true,
  },
  {
    position: 2,
    team: 'Saint George SC',
    played: 24,
    won: 15,
    drawn: 6,
    lost: 3,
    goalsFor: 41,
    goalsAgainst: 19,
    goalDifference: 22,
    points: 51,
    form: ['W', 'D', 'W', 'W', 'L'],
    logo: 'https://placehold.co/60x60/dc2626/ffffff?text=STG',
  },
  {
    position: 3,
    team: 'Ethiopian Coffee SC',
    played: 24,
    won: 14,
    drawn: 6,
    lost: 4,
    goalsFor: 38,
    goalsAgainst: 21,
    goalDifference: 17,
    points: 48,
    form: ['W', 'W', 'L', 'W', 'D'],
    logo: 'https://placehold.co/60x60/854d0e/ffffff?text=COF',
  },
  {
    position: 4,
    team: 'Fasil Kenema SC',
    played: 24,
    won: 13,
    drawn: 7,
    lost: 4,
    goalsFor: 35,
    goalsAgainst: 22,
    goalDifference: 13,
    points: 46,
    form: ['L', 'W', 'W', 'D', 'W'],
    logo: 'https://placehold.co/60x60/ca8a04/ffffff?text=FAS',
  },
  {
    position: 5,
    team: 'Hawassa Kenema SC',
    played: 24,
    won: 11,
    drawn: 8,
    lost: 5,
    goalsFor: 32,
    goalsAgainst: 24,
    goalDifference: 8,
    points: 41,
    form: ['D', 'W', 'L', 'D', 'W'],
    logo: 'https://placehold.co/60x60/047857/ffffff?text=HAW',
  }
];

export const mockNews: NewsArticle[] = [
  {
    id: 'news-1',
    title: 'The Waves of Tana Seal Thrilling 2-1 Victory Over Fasil Kenema',
    category: 'Match Report',
    summary: 'A second-half masterclass from Habtamu Taddese and Alelegn Azene secures all three points in the northern derby.',
    content: `In front of an electrified crowd of over 45,000 passionate supporters at the Bahir Dar International Stadium, Bahir Dar Kenema demonstrated supreme character to overcome Fasil Kenema 2-1.

Head Coach Degarege Yigzaw praised the disciplined pressing and offensive fluidity: "Our players showed the heart of true champions. The energy from the Lake Tana stands was extraordinary."`,
    author: 'BDK Media Directorate',
    publishedAt: '2026-09-22T10:00:00Z',
    image: 'https://images.unsplash.com/photo-1508098682722-e99c43a406b2?w=1200&auto=format&fit=crop&q=80',
    readTime: '3 min read',
    tags: ['EPL', 'Derby', 'MatchReport', 'Victory']
  },
  {
    id: 'news-2',
    title: 'Bahir Dar Stadium Upgrades Confirmed Ahead of CAF Confederation Cup Run',
    category: 'Club News',
    summary: 'Bahir Dar City Administration announces smart ticketing turnstiles and upgraded pitch maintenance equipment.',
    content: `The Bahir Dar City Administration and BDK SC management board have finalized modernization plans for the Bahir Dar International Stadium ahead of the upcoming continental CAF fixtures.

The project introduces contactless digital e-ticketing, LED perimeter advertising, and renewed floodlighting standards.`,
    author: 'Club Operations Desk',
    publishedAt: '2026-09-20T14:30:00Z',
    image: 'https://images.unsplash.com/photo-1522778119026-d647f0596c20?w=1200&auto=format&fit=crop&q=80',
    readTime: '4 min read',
    tags: ['Stadium', 'CAF', 'Infrastructure']
  },
  {
    id: 'news-3',
    title: 'Youth Academy Trials Open for Under-17 and Under-20 Prospects',
    category: 'Community',
    summary: 'BDK launches scouting and development trial sessions across Amhara region zones for aspiring young talent.',
    content: `Bahir Dar Kenema Football Academy invites emerging talents between the ages of 15 and 20 to participate in the 2026 Regional Talent Scouting Sessions. Outstanding players will receive full athletic and academic scholarships.`,
    author: 'Youth Development Academy',
    publishedAt: '2026-09-18T09:00:00Z',
    image: 'https://images.unsplash.com/photo-1574629810360-7efbbe195018?w=1200&auto=format&fit=crop&q=80',
    readTime: '2 min read',
    tags: ['Academy', 'Youth', 'Trials']
  }
];

export const mockTicketTiers: TicketTier[] = [
  {
    id: 'tier-regular',
    name: 'General Admission (Bleachers)',
    price: 100,
    description: 'East & West open terraces with vibrant fan club atmosphere and drum lines.',
    availableSeats: 35000,
    benefits: ['Entry to open terrace', 'Club cheer-card included']
  },
  {
    id: 'tier-covered',
    name: 'Covered Tribune',
    price: 300,
    description: 'Shaded seating with clear elevated views of the halfway line and player benches.',
    availableSeats: 8000,
    benefits: ['Covered sheltered seating', 'Dedicated turnstile entry', 'Concession access']
  },
  {
    id: 'tier-vip',
    name: 'VIP Lounge & Box',
    price: 1000,
    description: 'Exclusive padded seating, climate-controlled lounge, refreshments, and secure parking pass.',
    availableSeats: 500,
    benefits: ['VIP Lounge access', 'Complimentary food & drinks', 'Priority parking', 'Official match program']
  }
];

export const mockProducts: Product[] = [
  {
    id: 'prod-1',
    name: 'Official Home Jersey 2026/27 (Waves of Tana Blue & Gold)',
    category: 'Kits',
    price: 1800,
    originalPrice: 2200,
    image: 'https://images.unsplash.com/photo-1581655353564-df123a1eb820?w=600&auto=format&fit=crop&q=80',
    description: 'The authentic home match jersey featuring breathable moisture-wicking fabric and gold lake wave accents.',
    sizes: ['S', 'M', 'L', 'XL', '2XL'],
    inStock: true,
    rating: 4.9,
    isNewArrival: true,
    isBestSeller: true
  },
  {
    id: 'prod-2',
    name: 'Official Away Jersey 2026/27 (Tana Crest White)',
    category: 'Kits',
    price: 1800,
    originalPrice: 2200,
    image: 'https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?w=600&auto=format&fit=crop&q=80',
    description: 'Elegant white and deep teal away jersey with woven club crest and premium lightweight weave.',
    sizes: ['S', 'M', 'L', 'XL'],
    inStock: true,
    rating: 4.8,
    isNewArrival: true
  },
  {
    id: 'prod-3',
    name: 'BDK Heritage Track Jacket',
    category: 'Apparel',
    price: 2500,
    image: 'https://images.unsplash.com/photo-1556905055-8f358a7a47b2?w=600&auto=format&fit=crop&q=80',
    description: 'Warm fleece-lined pre-match presentation jacket with zip pockets and embroidered club crest.',
    sizes: ['M', 'L', 'XL'],
    inStock: true,
    rating: 4.7,
    isBestSeller: true
  },
  {
    id: 'prod-4',
    name: 'BDK Waves Scarf & Beanie Combo',
    category: 'Accessories',
    price: 750,
    image: 'https://images.unsplash.com/photo-1608256246200-53e635b5b65f?w=600&auto=format&fit=crop&q=80',
    description: 'High-density jacquard knit matchday scarf featuring "Waves of Tana" script paired with a matching beanie.',
    inStock: true,
    rating: 4.9
  },
  {
    id: 'prod-5',
    name: 'Commemorative Club Trophy Pin & Keychain',
    category: 'Memorabilia',
    price: 350,
    image: 'https://images.unsplash.com/photo-1584917865442-de89df76afd3?w=600&auto=format&fit=crop&q=80',
    description: 'Solid brass enamelled keychain and lapel pin commemorating club milestone seasons.',
    inStock: true,
    rating: 4.6
  }
];

export const mockUsers: User[] = [
  {
    id: 'u-admin',
    name: 'BDK Administrator',
    email: 'admin@bdk.et',
    role: 'admin',
    phoneNumber: '+251918000000',
    membershipId: 'BDK-GOLD-001',
    createdAt: '2026-01-01T00:00:00Z'
  },
  {
    id: 'u-fan',
    name: 'Yonas Abebe',
    email: 'fan@bdk.et',
    role: 'fan',
    phoneNumber: '+251911223344',
    membershipId: 'BDK-FAN-1048',
    createdAt: '2026-03-15T00:00:00Z'
  }
];
